version: '3' # 定义版本，不指定默认为版本 1，新版本功能更多

services:
  app:
    build: ./
    image: finance_backend:demo
    restart: always
    ports:
      - "9001:9001"

    command: bash -c "python3 /www/manage.py db upgrade && gunicorn -w 2 -b 0.0.0.0:9001 app:app"

    environment:
      FLASK_ENV: production
    volumes:
      - .:/www
    networks:
      - backend
    depends_on:
      - mysql
      - redis
      - celery

  celery:
    build: ./
    image: finance_backend:worker
    restart: always

    command: celery worker -A app.celery --loglevel=info --beat

    environment:
      FLASK_ENV: production
    volumes:
      - .:/www
    networks:
      - backend
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: finance
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - /data/stone/mysql_db:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

    networks:
      - backend

networks:
  backend:
