"""init

Revision ID: efb7ba9f7e7f
Revises: 
Create Date: 2020-09-17 14:41:14.452502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb7ba9f7e7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('search_code', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('search_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('stock_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('open', sa.Float(precision=2), nullable=True),
    sa.Column('close', sa.Float(precision=2), nullable=True),
    sa.Column('high', sa.Float(precision=2), nullable=True),
    sa.Column('low', sa.Float(precision=2), nullable=True),
    sa.Column('pre_close', sa.Float(precision=2), nullable=True),
    sa.Column('change', sa.Float(precision=2), nullable=True),
    sa.Column('change_percent', sa.Float(precision=2), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_history')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
